name: Rust Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Update submodules
        run: git submodule update --init --recursive
      - name: Build
        run: cargo build --verbose
      - name: Run unit tests
        run: cargo test --lib --verbose